In [10]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from PIL import Image

In [11]:
!pip install kaleido
import plotly.io as pio
pio.renderers.default = "colab"

Requirement already satisfied: kaleido in /usr/local/lib/python3.12/dist-packages (1.3.0)
Requirement already satisfied: choreographer>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from kaleido) (1.3.0)
Requirement already satisfied: logistro>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido) (3.11.9)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaleido) (26.2)
Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.3.0->kaleido) (4.10.0)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.3.0->kaleido) (4.1.1)

In [12]:
# Import Dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("evangower/english-premier-league-standings")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'english-premier-league-standings' dataset.
Path to dataset files: /kaggle/input/english-premier-league-standings

In [13]:
import os

files = os.listdir(path)
csv_files = [f for f in files if f.endswith('.csv')]

if csv_files:
    # Assuming there's at least one CSV file, take the first one.
    data_file_path = os.path.join(path, csv_files[0])
    df = pd.read_csv(data_file_path)
    print(df.head())
else:
    print("No CSV files found in the dataset directory.")

   season_end_year            team  position  played  won  drawn  lost  gf  \
0             1993  Manchester Utd         1      42   24     12     6  67
1             1993     Aston Villa         2      42   21     11    10  57
2             1993    Norwich City         3      42   21      9    12  61
3             1993       Blackburn         4      42   20     11    11  68
4             1993             QPR         5      42   17     12    13  63

   ga  gd  points                                 notes
0  31  36      84  → Champions League via league finish
1  40  17      74          → UEFA Cup via league finish
2  65  -4      72        → UEFA Cup via league finish 1
3  46  22      71                                   NaN
4  55   8      63                                   NaN

In [14]:
# Extract Liverpool's Data
lfc = df.query('team == "Liverpool"')
lfc

,season_end_year,team,position,played,won,drawn,lost,gf,ga,gd,points,notes
5,1993,Liverpool,6,42,16,11,15,62,55,7,59,NaN
29,1994,Liverpool,8,42,17,9,16,59,55,4,60,NaN
47,1995,Liverpool,4,42,21,11,10,65,37,28,74,→ UEFA Cup via league finish
68,1996,Liverpool,3,38,20,11,7,70,34,36,71,→ UEFA Cup Winners' Cup via cup win 1
89,1997,Liverpool,4,38,19,11,8,62,37,25,68,→ UEFA Cup via league finish
108,1998,Liverpool,3,38,18,11,9,68,42,26,65,→ UEFA Cup via league finish
132,1999,Liverpool,7,38,15,9,14,68,49,19,54,NaN
149,2000,Liverpool,4,38,19,10,9,51,30,21,67,→ UEFA Cup via league finish
168,2001,Liverpool,3,38,20,9,9,71,39,32,69,→ Champions League via league finish
187,2002,Liverpool,2,38,24,8,6,67,30,37,80,→ Champions League via league finish
210,2003,Liverpool,5,38,18,10,10,61,41,20,64,→ UEFA Cup via league finish
229,2004,Liverpool,4,38,16,12,10,55,37,18,60,→ Champions League via league finish
250,2005,Liverpool,5,38,17,7,14,52,41,11,58,→ Champions League 1
268,2006,Liverpool,3,38,25,7,6,57,25,32,82,→ Champions League via league finish
288,2007,Liverpool,3,38,20,8,10,57,27,30,68,→ Champions League via league finish
309,2008,Liverpool,4,38,21,13,4,67,28,39,76,→ Champions League via league finish
327,2009,Liverpool,2,38,25,11,2,77,27,50,86,→ Champions League via league finish
352,2010,Liverpool,7,38,18,9,11,61,35,26,63,→ Europa League via league finish 2
371,2011,Liverpool,6,38,17,7,14,59,44,15,58,NaN
393,2012,Liverpool,8,38,14,10,14,47,40,7,52,→ Europa League via cup win 1
412,2013,Liverpool,7,38,16,13,9,71,43,28,61,NaN
427,2014,Liverpool,2,38,26,6,6,101,50,51,84,→ Champions League via league finish
451,2015,Liverpool,6,38,18,8,12,52,48,4,62,→ Europa League via league finish 1
473,2016,Liverpool,8,38,16,12,10,63,50,13,60,NaN
489,2017,Liverpool,4,38,22,10,6,78,42,36,76,→ Champions League via league finish
509,2018,Liverpool,4,38,21,12,5,84,38,46,75,→ Champions League via league finish
527,2019,Liverpool,2,38,30,7,1,89,22,67,97,→ Champions League via league finish
546,2020,Liverpool,1,38,32,3,3,85,33,52,99,→ Champions League via league finish
568,2021,Liverpool,3,38,20,9,9,68,42,26,69,→ Champions League via league finish
587,2022,Liverpool,2,38,28,8,2,94,26,68,92,→ Champions League via league finish
610,2023,Liverpool,5,38,19,10,9,75,47,28,67,→ Europa League via league finish
628,2024,Liverpool,3,38,24,10,4,86,41,45,82,→ Champions League via league finish

In [15]:
# Add the last 2 seasons manually

# 1. Create a dictionary with the 2 new rows
new_data = {
    'season_end_year': ['2025', '2026'],
    'team': ['Liverpool', 'Liverpool'],
    'position': [1, 5],
    'played': [38, 38],
    'won': [25, 17],
    'drawn': [9, 9],
    'lost': [4, 12],
    'gf': [86, 63],
    'ga': [41, 53],
    'gd': [45, 10],
    'points': [84, 60],
      'notes': ['→ Champions League via league finish', '→ Champions League via league finish']
}


# 2. Convert the new data to a DataFrame
df_new = pd.DataFrame(new_data)

# 3. Concatenate them vertically
lfc_new = pd.concat([lfc, df_new], ignore_index=True)

In [16]:
lfc_new

,season_end_year,team,position,played,won,drawn,lost,gf,ga,gd,points,notes
0,1993,Liverpool,6,42,16,11,15,62,55,7,59,NaN
1,1994,Liverpool,8,42,17,9,16,59,55,4,60,NaN
2,1995,Liverpool,4,42,21,11,10,65,37,28,74,→ UEFA Cup via league finish
3,1996,Liverpool,3,38,20,11,7,70,34,36,71,→ UEFA Cup Winners' Cup via cup win 1
4,1997,Liverpool,4,38,19,11,8,62,37,25,68,→ UEFA Cup via league finish
5,1998,Liverpool,3,38,18,11,9,68,42,26,65,→ UEFA Cup via league finish
6,1999,Liverpool,7,38,15,9,14,68,49,19,54,NaN
7,2000,Liverpool,4,38,19,10,9,51,30,21,67,→ UEFA Cup via league finish
8,2001,Liverpool,3,38,20,9,9,71,39,32,69,→ Champions League via league finish
9,2002,Liverpool,2,38,24,8,6,67,30,37,80,→ Champions League via league finish
10,2003,Liverpool,5,38,18,10,10,61,41,20,64,→ UEFA Cup via league finish
11,2004,Liverpool,4,38,16,12,10,55,37,18,60,→ Champions League via league finish
12,2005,Liverpool,5,38,17,7,14,52,41,11,58,→ Champions League 1
13,2006,Liverpool,3,38,25,7,6,57,25,32,82,→ Champions League via league finish
14,2007,Liverpool,3,38,20,8,10,57,27,30,68,→ Champions League via league finish
15,2008,Liverpool,4,38,21,13,4,67,28,39,76,→ Champions League via league finish
16,2009,Liverpool,2,38,25,11,2,77,27,50,86,→ Champions League via league finish
17,2010,Liverpool,7,38,18,9,11,61,35,26,63,→ Europa League via league finish 2
18,2011,Liverpool,6,38,17,7,14,59,44,15,58,NaN
19,2012,Liverpool,8,38,14,10,14,47,40,7,52,→ Europa League via cup win 1
20,2013,Liverpool,7,38,16,13,9,71,43,28,61,NaN
21,2014,Liverpool,2,38,26,6,6,101,50,51,84,→ Champions League via league finish
22,2015,Liverpool,6,38,18,8,12,52,48,4,62,→ Europa League via league finish 1
23,2016,Liverpool,8,38,16,12,10,63,50,13,60,NaN
24,2017,Liverpool,4,38,22,10,6,78,42,36,76,→ Champions League via league finish
25,2018,Liverpool,4,38,21,12,5,84,38,46,75,→ Champions League via league finish
26,2019,Liverpool,2,38,30,7,1,89,22,67,97,→ Champions League via league finish
27,2020,Liverpool,1,38,32,3,3,85,33,52,99,→ Champions League via league finish
28,2021,Liverpool,3,38,20,9,9,68,42,26,69,→ Champions League via league finish
29,2022,Liverpool,2,38,28,8,2,94,26,68,92,→ Champions League via league finish
30,2023,Liverpool,5,38,19,10,9,75,47,28,67,→ Europa League via league finish
31,2024,Liverpool,3,38,24,10,4,86,41,45,82,→ Champions League via league finish
32,2025,Liverpool,1,38,25,9,4,86,41,45,84,→ Champions League via league finish
33,2026,Liverpool,5,38,17,9,12,63,53,10,60,→ Champions League via league finish

In [17]:
lfc_new.dtypes

season_end_year    object
team               object
position            int64
played              int64
won                 int64
drawn               int64
lost                int64
gf                  int64
ga                  int64
gd                  int64
points              int64
notes              object
dtype: object

In [18]:
# Liverpool's Inconsistent Trend over the years

lfc_new['season_end_year'] = pd.to_numeric(lfc_new['season_end_year']) # Ensure season_end_year is numeric

fig = px.scatter(
    lfc_new,
    x='season_end_year',
    y='points',
    title="Liverpool's Inconsistency in the Premier League Era",
    color='position',  # Color the line based on position
    color_continuous_scale='RdYlGn_r', # Green for low position, Red for high position
    hover_data={'position': True} # Show position on hover
)

fig.update_layout(
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    template="plotly_white"
)

fig.update_traces(
    mode="lines+markers" # Show markers at each data point
)
img = Image.open("/content/drive/MyDrive/Sports Analytics/Stats_vs_Eye_Test_removebg.png")

fig.add_layout_image(
    dict(
        source=img,
        xref="paper",
        yref="paper",
        x=1.15,          # move slightly beyond right edge
        y=-0.20,         # move slightly below plot
        xanchor="right",
        yanchor="bottom",
        sizex=0.21,
        sizey=0.21,
        sizing="contain",
        opacity=0.8,
        layer="above"
    )
)

fig.show()

In [19]:
#League Position over time

# 1. Create a basic line chart with markers
fig2 = px.line(
    lfc_new,
    x='season_end_year',
    y='position',
    markers=True,
    title="Liverpool's League Position Over Time",
    labels={'position': 'League Finish', 'season_end_year': 'Season'}
)

# 2. Crucial step: Invert the Y-axis so 1st place is at the top
fig2.update_yaxes(autorange="reversed", tickmode='linear', dtick=1)

# 3. Add a shaded background area for the Top 4 (Champions League spots)
fig2.add_hrect(
    y0=0.5, y1=4.5, # Covers positions 1 through 4
    fillcolor="lightgreen", opacity=0.2,
    layer="below", line_width=0,
    annotation_text=" Top 4",
    annotation_position="bottom left"
)

fig2.update_layout(
    template="plotly_white",
    xaxis_showgrid=True,
    yaxis_showgrid=False
)

fig2.add_annotation(
    x=2026,
    y=5,
    text="Ucl Spot",
    showarrow=False,
    xanchor="left",
    yanchor="top",
    font=dict(color="black")
)

img = Image.open("/content/drive/MyDrive/Sports Analytics/Stats_vs_Eye_Test_removebg.png")

fig2.add_layout_image(
    dict(
        source=img,
        xref="paper",
        yref="paper",
        x=1.13,          # move slightly beyond right edge
        y=-0.12,         # move slightly below plot
        xanchor="right",
        yanchor="bottom",
        sizex=0.23,
        sizey=0.23,
        sizing="contain",
        opacity=0.8,
        layer="above"
    )
)

fig2.show()

In [20]:
#Trend over the last 8 seasons

lfc_new['season_end_year'] = pd.to_numeric(lfc_new['season_end_year'])
recent = lfc_new[lfc_new['season_end_year'] > 2018]
recent

fig = px.line(
    recent,
    x='season_end_year',
    y='points',
    title='League Table Trend'
    )

fig.update_layout(
    xaxis_showgrid=True,
    yaxis_showgrid=True
)

fig.update_layout(
    title="Liverpool's Points Trend Over the Last 8 Seasons",
    template="plotly_white"
)

fig.update_traces(
    mode="lines+markers"
)

fig.add_annotation(
    x=2020,
    y=99,
    text="19th Title Win",
    showarrow=False,
    xanchor="left",
    yanchor="bottom"
)

fig.add_annotation(
    x=2021,
    y=69,
    text="30 pt drop",
    showarrow=False,
    xanchor="right",
    yanchor="bottom",
    font=dict(color="red")
)

fig.add_annotation(
    x=2022,
    y=92,
    text="FA, Carabao & 2nd",
    showarrow=False,
    xanchor="left",
    yanchor="bottom"
)

fig.add_annotation(
    x=2023,
    y=67,
    text="25 pt drop",
    showarrow=False,
    xanchor="right",
    yanchor="top",
    font=dict(color="red")
)

fig.add_annotation(
    x=2025,
    y=84,
    text="20th Title Win",
    showarrow=False,
    xanchor="left",
    yanchor="bottom"
)

fig.add_annotation(
    x=2026,
    y=60,
    text="24 pt drop",
    showarrow=False,
    xanchor="right",
    yanchor="top",
    font=dict(color="red")
)


img = Image.open("/content/drive/MyDrive/Sports Analytics/Stats_vs_Eye_Test_removebg.png")

fig.add_layout_image(
    dict(
        source=img,
        xref="paper",
        yref="paper",
        x=1.13,          # move slightly beyond right edge
        y=-0.12,         # move slightly below plot
        xanchor="right",
        yanchor="bottom",
        sizex=0.23,
        sizey=0.23,
        sizing="contain",
        opacity=0.8,
        layer="above"
    )
)
fig.show()

In [21]:
#Import Injuries Dataset

lfc_injuries = pd.read_csv('/content/drive/MyDrive/Sports Analytics/liverpool_injuries.csv', encoding='latin1')

In [22]:
lfc_injuries.dropna(inplace=True)
lfc_injuries

   Season                     Name  Days Injured
0   25/26     Giorgi Mamardashvili           2.0
1   25/26                  Alisson          12.0
2   25/26           Giovanni Leoni          33.0
3   25/26                Joe Gomez           6.0
4   25/26         Jeremie Frimpong          14.0
5   25/26            Conor Bradley          21.0
6   25/26         Ryan Gravenberch           1.0
7   25/26              Wataru Endo          18.0
8   25/26          Stefan Bajcetic          38.0
9   25/26      Alexis Mac Allister           1.0
10  25/26             Curtis Jones           2.0
11  25/26            Florian Wirtz           5.0
12  25/26               Cody Gakpo           2.0
13  25/26            Mohamed Salah           3.0
14  25/26          Federico Chiesa           1.0
15  25/26           Alexander Isak          18.0
16  25/26             Hugo Ekitike           8.0
17  20/21                  Alisson           4.0
18  20/21          Virgil van Dijk          32.0
19  20/21                Joe Gomez          30.0
20  20/21               Ozan Kabak           5.0
21  20/21               Joel Matip          27.0
22  20/21          Kostas Tsimikas          13.0
23  20/21   Trent Alexander-Arnold           2.0
24  20/21               Naby Keta          19.0
25  20/21  Alex Oxlade-Chamberlain          11.0
26  20/21                   Thiago          12.0
27  20/21                  Fabinho           8.0
28  20/21               Diogo Jota          17.0
29  20/21             James Milner           7.0
30  20/21            Mohamed Salah           1.0
31  20/21          Xherdan Shaqiri           6.0
32  20/21         Roberto Fiirmino           2.0
33  20/21         Jordan Henderson          12.0
34  22/23        Caoimhin Kelleher           6.0
35  22/23          Virgil van Dijk           4.0
36  22/23           Andy Robertson           2.0
37  22/23                Joe Gomez           4.0
38  22/23          Stefan Bajcetic          12.0
39  22/23               Joel Matip           3.0
40  22/23                Luis Diaz          21.0
41  22/23          Ibrahima Konate          16.0
42  22/23               Naby Keta          28.0
43  22/23  Alex Oxlade-Chamberlain           9.0
44  22/23                   Thiago          19.0
45  22/23               Diogo Jota          16.0
46  22/23             James Milner           7.0
47  22/23             Curtis Jones           9.0
48  22/23         Roberto Fiirmino           5.0
49  22/23         Jordan Henderson           1.0
50  22/23              Arthur Melo          15.0
51  22/23             Darwin Nunez           6.0

In [23]:
# Number of Days injured by Season

season_total_injuries = lfc_injuries.groupby('Season')['Days Injured'].sum().reset_index()

fig = px.bar(
    season_total_injuries,
    x='Season',
    y='Days Injured',
    text='Days Injured',
    title="Were Injuries a Factor? Examining Liverpool's Three Dip Seasons"
)

fig.update_layout(
    xaxis_showgrid=True,
    yaxis_showgrid=True
)

fig.update_layout(
    template="plotly_white"
)

fig.update_traces(
    textposition="outside"
)

img = Image.open("/content/drive/MyDrive/Sports Analytics/Stats_vs_Eye_Test_removebg.png")

fig.add_layout_image(
    dict(
        source=img,
        xref="paper",
        yref="paper",
        x=1.13,          # move slightly beyond right edge
        y=-0.12,         # move slightly below plot
        xanchor="right",
        yanchor="bottom",
        sizex=0.23,
        sizey=0.23,
        sizing="contain",
        opacity=0.8,
        layer="above"
    )
)

fig.show()

In [24]:
# Number of Injuries by season

injured_players_count = lfc_injuries.groupby('Season')['Name'].nunique().reset_index()
injured_players_count.rename(columns={'Name': 'Injured Players'}, inplace=True)

fig = px.bar(
    injured_players_count,
    x='Season',
    y='Injured Players',
    text='Injured Players',
    title='Number of Unique Injured Players Per Season'
)

fig.update_layout(
    xaxis_showgrid=True,
    yaxis_showgrid=True
)

fig.update_layout(
    title="Liverpool's Three Dip Seasons: Total Number of Injured Players",
    template="plotly_white"
)

fig.update_traces(
    textposition="outside"
)

img = Image.open("/content/drive/MyDrive/Sports Analytics/Stats_vs_Eye_Test_removebg.png")

fig.add_layout_image(
    dict(
        source=img,
        xref="paper",
        yref="paper",
        x=1.13,          # move slightly beyond right edge
        y=-0.12,         # move slightly below plot
        xanchor="right",
        yanchor="bottom",
        sizex=0.23,
        sizey=0.23,
        sizing="contain",
        opacity=0.8,
        layer="above"
    )
)

fig.show()